version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: memori-postgres
    environment:
      POSTGRES_USER: memori
      POSTGRES_PASSWORD: memori
      POSTGRES_DB: memori
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memori"]
      interval: 5s
      timeout: 5s
      retries: 10

  cache:
    # Redis-compatible image; swap to Valkey if preferred
    image: redis:7-alpine
    container_name: memori-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
